/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        // Material 3 tokens — bound to CSS variables so light/dark just works
        background: "hsl(var(--background) / <alpha-value>)",
        "on-background": "hsl(var(--on-background) / <alpha-value>)",
        surface: "hsl(var(--surface) / <alpha-value>)",
        "on-surface": "hsl(var(--on-surface) / <alpha-value>)",
        "on-surface-variant": "hsl(var(--on-surface-variant) / <alpha-value>)",
        "surface-variant": "hsl(var(--surface-variant) / <alpha-value>)",
        "surface-container-lowest":  "hsl(var(--surface-container-lowest)  / <alpha-value>)",
        "surface-container-low":     "hsl(var(--surface-container-low)     / <alpha-value>)",
        "surface-container":         "hsl(var(--surface-container)         / <alpha-value>)",
        "surface-container-high":    "hsl(var(--surface-container-high)    / <alpha-value>)",
        "surface-container-highest": "hsl(var(--surface-container-highest) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "on-primary": "hsl(var(--on-primary) / <alpha-value>)",
        "primary-container": "hsl(var(--primary-container) / <alpha-value>)",
        "on-primary-container": "hsl(var(--on-primary-container) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "on-secondary": "hsl(var(--on-secondary) / <alpha-value>)",
        "secondary-container": "hsl(var(--secondary-container) / <alpha-value>)",
        "on-secondary-container": "hsl(var(--on-secondary-container) / <alpha-value>)",
        tertiary: "hsl(var(--tertiary) / <alpha-value>)",
        "on-tertiary": "hsl(var(--on-tertiary) / <alpha-value>)",
        "tertiary-container": "hsl(var(--tertiary-container) / <alpha-value>)",
        "on-tertiary-container": "hsl(var(--on-tertiary-container) / <alpha-value>)",
        error: "hsl(var(--error) / <alpha-value>)",
        "on-error": "hsl(var(--on-error) / <alpha-value>)",
        "error-container": "hsl(var(--error-container) / <alpha-value>)",
        "on-error-container": "hsl(var(--on-error-container) / <alpha-value>)",
        success: "hsl(var(--success) / <alpha-value>)",
        "on-success": "hsl(var(--on-success) / <alpha-value>)",
        "success-container": "hsl(var(--success-container) / <alpha-value>)",
        "on-success-container": "hsl(var(--on-success-container) / <alpha-value>)",
        outline: "hsl(var(--outline) / <alpha-value>)",
        "outline-variant": "hsl(var(--outline-variant) / <alpha-value>)",

        // shadcn compat aliases (so existing components keep working)
        border:           "hsl(var(--outline-variant) / <alpha-value>)",
        input:            "hsl(var(--outline-variant) / <alpha-value>)",
        ring:             "hsl(var(--primary) / <alpha-value>)",
        foreground:       "hsl(var(--on-surface) / <alpha-value>)",
        muted:            { DEFAULT: "hsl(var(--surface-container) / <alpha-value>)", foreground: "hsl(var(--on-surface-variant) / <alpha-value>)" },
        accent:           { DEFAULT: "hsl(var(--primary) / <alpha-value>)",           foreground: "hsl(var(--on-primary) / <alpha-value>)" },
        destructive:      { DEFAULT: "hsl(var(--error) / <alpha-value>)",             foreground: "hsl(var(--on-error) / <alpha-value>)" },
        popover:          { DEFAULT: "hsl(var(--surface-container) / <alpha-value>)", foreground: "hsl(var(--on-surface) / <alpha-value>)" },
        card:             { DEFAULT: "hsl(var(--surface-container) / <alpha-value>)", foreground: "hsl(var(--on-surface) / <alpha-value>)" },
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
      },
      backgroundImage: {
        "grad-primary": "linear-gradient(135deg, hsl(var(--grad-from)), hsl(var(--grad-to)))",
        "grad-mesh":    "radial-gradient(at 0% 0%, hsl(var(--primary) / .12) 0px, transparent 50%), radial-gradient(at 100% 100%, hsl(var(--secondary) / .10) 0px, transparent 50%)",
      },
      boxShadow: {
        "soft":    "0 1px 3px 0 rgb(0 0 0 / .05), 0 1px 2px 0 rgb(0 0 0 / .03)",
        "soft-lg": "0 4px 6px -1px rgb(0 0 0 / .07), 0 2px 4px -2px rgb(0 0 0 / .05)",
        "glow":    "0 8px 24px -8px hsl(var(--primary) / .40)",
        "glow-lg": "0 0 0 1px hsl(var(--primary) / .25), 0 12px 32px -8px hsl(var(--primary) / .50)",
      },
      keyframes: {
        "fade-in":  { "0%": { opacity: "0", transform: "translateY(4px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "shimmer":  { "100%": { transform: "translateX(100%)" } },
        "slide-up": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
      },
      animation: {
        "fade-in":  "fade-in .25s ease-out",
        "shimmer":  "shimmer 1.6s infinite",
        "slide-up": "slide-up .3s cubic-bezier(.16,1,.3,1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
